---
  path: automation
  title: Automation
  icon: mdi:home-automation
  cards:
    - type: vertical-stack
      cards:
        - type: entities
          title: Others
          show_header_toggle: false
          entities:
              - automation.people_not_at_home
    - type: vertical-stack
      cards:
        - type: entities
          title: System
          show_header_toggle: false
          entities:
              - automation.system_upgrade_alert
              - automation.zigbee_map_actualiseren
    - title: Zigbee2mqtt
      type: entities
      show_header_toggle: false
      entities:
        - entity: sensor.zigbee2mqtt_bridge_state
        - entity: sensor.zigbee2mqtt_version
        - entity: sensor.coordinator_version
        - entity: input_select.zigbee2mqtt_log_level
        - type: divider
        - entity: switch.zigbee2mqtt_main_join
        - entity: timer.zigbee_permit_join
        - type: divider
        - entity: input_text.zigbee2mqtt_old_name
        - entity: input_text.zigbee2mqtt_new_name
        - entity: script.zigbee2mqtt_rename
        - type: divider
        - entity: input_text.zigbee2mqtt_remove
        - entity: script.zigbee2mqtt_remove
